-- Migración: Tabla de usuarios (compatible con esquema Supabase)
-- Almacena los datos de los usuarios autenticados con Firebase

CREATE TABLE IF NOT EXISTS public.tbl_usuarios (
  id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_supabase TEXT NULL, -- UID de Supabase Auth (si se usa)
  nombre TEXT NOT NULL, -- Nombre completo del usuario (displayName de Firebase)
  correo TEXT NOT NULL, -- Email del usuario
  fecha_registro TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT NOW(),
  foto_perfil TEXT NULL, -- URL de la foto de perfil (photoURL de Firebase)
  id_estado BIGINT NULL, -- Estado del usuario (activo/inactivo, etc.)
  ultimo_login TIMESTAMP WITHOUT TIME ZONE NULL,
  firebase_uid TEXT NULL, -- UID único de Firebase Authentication
  CONSTRAINT tbl_usuarios_pkey PRIMARY KEY (id_usuario),
  CONSTRAINT tbl_usuarios_correo_key UNIQUE (correo),
  CONSTRAINT tbl_usuarios_id_supabase_key UNIQUE (id_supabase),
  CONSTRAINT tbl_usuarios_nombre_key UNIQUE (nombre)
  -- CONSTRAINT tbl_usuarios_id_estado_fkey FOREIGN KEY (id_estado) REFERENCES tbl_estados (id_estado)
  -- Nota: Descomentar la línea anterior si existe tbl_estados
) TABLESPACE pg_default;

-- Índice para búsquedas rápidas por Firebase UID
CREATE INDEX IF NOT EXISTS idx_usuarios_firebase_uid ON public.tbl_usuarios(firebase_uid);

-- Índice para búsquedas por id_supabase
CREATE INDEX IF NOT EXISTS idx_usuarios_id_supabase ON public.tbl_usuarios(id_supabase);

COMMENT ON TABLE public.tbl_usuarios IS 'Usuarios registrados desde Firebase/Supabase Authentication';
COMMENT ON COLUMN public.tbl_usuarios.firebase_uid IS 'UID único proporcionado por Firebase Auth';
COMMENT ON COLUMN public.tbl_usuarios.id_supabase IS 'UID de Supabase Auth (si aplica)';
COMMENT ON COLUMN public.tbl_usuarios.correo IS 'Correo electrónico del usuario';
COMMENT ON COLUMN public.tbl_usuarios.nombre IS 'Nombre para mostrar del usuario';
COMMENT ON COLUMN public.tbl_usuarios.foto_perfil IS 'URL de la foto de perfil del usuario';
